### ISSUE TITLE
Componente de Upload com design dinâmico e suporte para múltiplo.

### ISSUE THREAD

**Issue by eliasassuncao** [bildvitta/asteroid#170]
No portal, usamos em vários lugares o campo de upload, porém com design diferente, como as imagens a seguir. Foi criado um componente, que é responsável por fazer o upload de arquivos pro s3, porém você pode passar o estilo que preferir para ele.

![image](https://user-images.githubusercontent.com/29342573/110133377-0283be00-7dab-11eb-96b0-7a9befe8884d.png)

![image](https://user-images.githubusercontent.com/29342573/110133873-9190d600-7dab-11eb-985f-45b5ebd42561.png)

**Comment by DouglasCalora** [comment]
Pode ser um `QasCustomUpload.vue` ou pensa em ser apenas um unico `QasUpload`? @eliasassuncao

**Comment by eliasassuncao** [comment]
Acho que é melhor fazer um custom.

**Comment by caiotarifa** [comment]
Concordo com um `QasCustomUpload.vue` que implemente o mesmo código do `QasUpload.vue` (podemos criar um mixing para isso).
