### ISSUE TITLE
Correção no helper de handleHistory

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#174]

**Comment by DouglasCalora** [comment]
@leonardoMarco20  Quando for abrir uma issue por favor adicione uma descrição completa para qualquer um que veja possa entender/desenvolver, que arquivos de boot? cadê as tags corretas? é um bug? é uma feature? esta em triagem?

**Comment by leonardoMarco20** [comment]
No Almobi o botão de voltar no componente de qas-header não está aparecendo, isso ocorre porque a inicialização do handleHistory não é feita. No Steroids havia um arquivo router.js, onde era feito essa inicialização, no Asteroid ele não existe.

**Comment by caiotarifa** [comment]
@DouglasCalora confirma que é um bug?
@leonardoMarco20 já temos um código de solução para isso?

**Comment by leonardoMarco20** [comment]
@caiotarifa ainda não, mas acredito que possa ser a falta dos handlers, em historyHandler.js há um comentário solicitando a retirada dos handlers em history.js. 

Era dessa forma que estava no steroids:
![image](https://user-images.githubusercontent.com/50151901/112684635-107caa00-8e52-11eb-8dfa-93aee2b25584.png)
