### ISSUE TITLE
Alterações no componente qas-uploader

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#180]
Alterações no componente qas-uploader:

- Tornar o header todo clicável, não apenas o ícone de adicionar arquivo.

- Tornar a listagem dos itens adicionados na horizontal.
![image](https://user-images.githubusercontent.com/50151901/112632664-28830800-8e17-11eb-8b08-18d6389d63b7.png)

**Comment by caiotarifa** [comment]
Por mim, podemos seguir em frente com a modificação, faz sentido!
