### ISSUE TITLE
Alteração no componente qas-tabs-generator 

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#181]
Requisição do design : Todas as palavras precisam estar na cor primary e BOLD nas selecionadas.

- Criar prop para cor de texto das labels. 
- Deixar texto da tab selecionada BOLD.

![image](https://user-images.githubusercontent.com/50151901/112634106-f1adf180-8e18-11eb-951a-66ed30035fc8.png)

**Comment by caiotarifa** [comment]
Acho que podemos seguir, o próprio Quasar já não tem uma proposta para mudar a cor? O que faremos é deixar `primary` por padrão (além do negrito quando selecionado), certo?

**Comment by leonardoMarco20** [comment]
Concordo, podemos deixar `primary` por padrão mesmo e Bold quando selecionado.
