### ISSUE TITLE
Alteração no componente qas-settings

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#182]
Requisição do design : Dropdown menu deve ficar fixo em uma posição. Por exemplo sempre alinhado à direita. 

![image](https://user-images.githubusercontent.com/50151901/112636097-6124e080-8e1b-11eb-9608-5afd5d97916d.png)

- Criar prop de posição do dropdown menu. 
- Usá-la em `<q-menu self="prop_aqui" /> `

**Comment by caiotarifa** [comment]
Como o Quasar lida com isso? Eu acho esse assunto bem delicado, pois se não tiver espaço para o menu abrir para um lado, temos que abrir para o outro (assim como acontece com cima/baixo).

**Comment by DouglasCalora** [comment]
Existe o problema que o caio disse, porém o que da pra resolver é quando tem espaço ele tem este comportamento de abrir sempre alinhado a direita, quando falta espaço ele abre onde conseguir, o que acham? @caiotarifa @leonardoMarco20

**Comment by leonardoMarco20** [comment]
Mas esse já é o comportamento dele não? @DouglasCalora 

Esse ponto foi levantado porque no almobi, temos o qas-settings na parte superior direita da tela, em alguns monitores dependendo da resolução, sobra um espaço a direita que permite o componente abrir o dropdown alinhando a esquerda.
