### ISSUE TITLE
Refatoração do historyHandler

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#188]
No momento, o histórico de páginas acessadas está sendo guardado em 2 locais diferentes, em $history e em history(Vue.observable). Nos arquivos history.js e  historyHandler.js.

Devemos refatorar e armazenar em apenas um lugar para evitar confusão e possíveis bugs.

**Comment by DouglasCalora** [comment]
Isto seria um `bug` não `feature`

**Comment by leonardoMarco20** [comment]
Estou fechando a `issue` pois já foi feita.
