### ISSUE TITLE
Adjust index.scss background color

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#189]
Ajustar a cor de background no index.scss, ela está fixa $grey-1, isso está gerando uma sutil diferença nas cores de fundo com os componentes no almobi.

Deixando como transparente o problema é resolvido e não fica branco como imaginávamos. 

![image](https://user-images.githubusercontent.com/50151901/113203606-a04f9900-9242-11eb-8f40-348f1decb44e.png)

![image](https://user-images.githubusercontent.com/50151901/113203723-c2e1b200-9242-11eb-9274-4c119882abb4.png)

**Comment by DouglasCalora** [comment]
@leonardoMarco20 Isto foi alinhado com os demais designers?

**Comment by leonardoMarco20** [comment]
@DouglasCalora  Isso é algo que pode ser alterado no projeto, se ele ficar transparent, ele ficara com a cor do background padão do projeto.
