### ISSUE TITLE
qas-app-bar - Add prop para atribuir um route

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#192]
Hoje o componente qas-app-bar esta redirecionando para um link externo, ele tem apenas uma prop href. No Almobi precisamos redirecionar para um link interno e para isso o componente deve ter uma prop para dizer qual rota deve ser redirecionado.

**Comment by DouglasCalora** [comment]
@leonardoMarco20  Mas este componente não foi criado justamente para navegar entre sistemas e não entre o sistema em si?

**Comment by leonardoMarco20** [comment]
@DouglasCalora, alinhei com o pessoal, essa alteração já não faz mais sentido. Eu fecho a issue?
