### ISSUE TITLE
Adicionar padrão `$_` para mixins

### ISSUE THREAD

**Issue by DouglasCalora** [bildvitta/asteroid#198]
Temos alguns mixins no `almobi` e `assistencia-digital` (que são os mesmos). Lá utilizamos o padrão `$_` para que fique fácil de identificar que é um mixin. Estes mixins faz sentido estarem dentro do asteroid, mas para isto precisaria utilizar o padrão `$_` e no asteroid está sem padrão. A ideia é subistituir os mixins atuais do asteroid por este padrão e adicionar os mixins que estamos utilizando no almobi e assistencia lá para não ter que ficar copiando de um projeto para o outro.

**Comment by caiotarifa** [comment]
De acordo.

**Comment by DouglasCalora** [comment]
Na nova versão do asteroid estão todos com o novo padrão `mx_` por conta do vue deixar `$` e `_` como propriedades reservadas.
