### ISSUE TITLE
Adicionar helpers utilizado no almobi  e assistencia-digital no asteroid

### ISSUE THREAD

**Issue by DouglasCalora** [bildvitta/asteroid#199]
Existem alguns helpers que utilizamos no almobi e assistencia que faciliam o desenvolvimento das telas, que talvez poderiam estar dentro do asteroid para não ter que ficar copiando de outros lugares.

**Comment by DouglasCalora** [comment]
Exemplo: 
![image](https://user-images.githubusercontent.com/32134017/113726536-b2aa5680-96ca-11eb-8e58-46526832d3f3.png)
Um helper para filtrar os campos que eu quero na tela a partir do retorno dos fields.

**Comment by caiotarifa** [comment]
Acho válido, consegue abrir um PR com esses helpers para olharmos um a um?

**Comment by gqueiroz1** [comment]
Estou fechando a issue pois já está feito
