### ISSUE TITLE
Criar componente qas-card

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#206]
Criar um componente de card

O card é dividido em 3 partes - header, content e bottom. (um slot para cada)

Em header por default o card teria uma imagem ou um carousel se tiver mais fotos.

Content terá 2 slots - infoHeader e infoContent. infoHeader para título e subtitulo, e infoContent para outras informações.

O bottom seria um espaço para botões de ação/menu

![image](https://user-images.githubusercontent.com/50151901/114608204-cf6aff00-9c73-11eb-8312-80c8531ff5d5.png)

**Comment by caiotarifa** [comment]
Show, mas o _footer_ não precisa de um _slot_ tb? E eu tiraria o prefixo "info" dos slots.

**Comment by leonardoMarco20** [comment]
Sim o footer tem, seria a parte das ações.
