### ISSUE TITLE
Criar componente qas-textTruncate

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#207]
Criar um componente para truncar um determinado texto.

Se o texto atingir o limite da `div`, deverá ser truncado com `ellipsis` e criar um link ('Ver mais') para visualizar o texto inteiro em um dialog.
 
![image](https://user-images.githubusercontent.com/50151901/114608850-85364d80-9c74-11eb-807e-9754b7ad9bb8.png)

![image](https://user-images.githubusercontent.com/50151901/114609101-ca5a7f80-9c74-11eb-8a69-3d33b7a01b1e.png)

**Comment by caiotarifa** [comment]
De acordo, mas eu chamaria de `QasTrucate` apenas. E precisa ter props `tag` e `label` para escolher qual tag englobará o texto (padrão pode ser `p`) e o texto de `Ver mais`.

**Comment by DouglasCalora** [comment]
@leonardoMarco20 Eu precisei fazer um ajuste desse componente no `assistencia` para ele funcionar também nas tabelas de listagem passando um valor fixo, seria interessante utilizar o do assistencia.

**Comment by plowzzer** [comment]
`QasTruncate`

**Comment by plowzzer** [comment]
@DouglasCalora ... pode mostrar como ficou o componente aqui ?
