### ISSUE TITLE
Criar componente itemLabelRedirect

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#208]
Criar um componente que faça um redirecionamento.

Por default ele será uma label, mas pode ser qualquer tipo de elemento.

No almobi utilizamos muito esse componente em títulos de nome  e em lista de badges em tabelas.

Podemos mudar o nome para um mais abstrato.

![image](https://user-images.githubusercontent.com/50151901/114609627-65535980-9c75-11eb-90a9-a018bc88f4ae.png)

**Comment by caiotarifa** [comment]
Não entendi, redirecionamento ou link? Qual a diferença entre esse componente e o `router-link`?

**Comment by plowzzer** [comment]
Esse `item-label-redirect` é próprio para o que o Lucas quer... tudo que for label tem que estar em negrito e fazer o redirect para o que o label esta descrevendo
A diferença é que o componente esta pronto, no router-link teria que passar a classe `text-bold` sempre

**Comment by caiotarifa** [comment]
É um componente apenas para não termos que inserir a classe `text-bold`?
