### ISSUE TITLE
Criar o componente de dropdown

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#209]
Criar um componente de dropdown seguindo o padrão de design (deixar sempre a opção de delete por último e sempre aparecer)

![image](https://user-images.githubusercontent.com/50151901/114612819-f972f000-9c78-11eb-9ddb-90e2956debcf.png)

**Comment by caiotarifa** [comment]
Seria um "wrap component", certo? Eu não deixaria o "Excluir" dentro do componente, não faz muito sentido por mais que ele aparece algumas vezes. Se é um dropdown, é apenas um dropdown.

**Comment by plowzzer** [comment]
Caio, o problema é o Delete ou o Componente, fiquei meio que na duvida...

**Comment by plowzzer** [comment]
Caso o problema seja o delete, eu deixaria ele ali pela mesma lógica de deixar o delete na tabela...

**Comment by leonardoMarco20** [comment]
Como o delete é o diferencial não compensaria criar esse componente, vou fechar a issue.
