### ISSUE TITLE
Criar componente de Tip

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#210]
Criar um componente de tip. 

O componente pode ter um título uma descrição e botões de ações.

Terá 3 slots - title, text e actions.

![image](https://user-images.githubusercontent.com/50151901/114614600-1f998f80-9c7b-11eb-9f76-74fbae99c6a5.png)

**Comment by caiotarifa** [comment]
Existe algum componente base com esse estilo já?

**Comment by plowzzer** [comment]
Sim... esta pronto no Almobi
