### ISSUE TITLE
Criar componente gallery

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#211]
Criar componente gallery.

Lista de cards de fotos com um botão de 'carregar mais'. A quantidade carregada é dinâmica.

Visualização da foto - dialog + carousel.  

**Componente iniciado**

![image](https://user-images.githubusercontent.com/50151901/114615559-37254800-9c7c-11eb-8659-9fbc919b9a1e.png)

**Componente após clicar em ver mais**

![image](https://user-images.githubusercontent.com/50151901/114615822-853a4b80-9c7c-11eb-915b-924143a8c194.png)

**Visualização da foto**

![image](https://user-images.githubusercontent.com/50151901/114616049-c7fc2380-9c7c-11eb-8611-2b3ed0bce3e1.png)

**Comment by caiotarifa** [comment]
Temos algo parecido no Portal CMS, não temos @eliasassuncao?
