### ISSUE TITLE
Adaptar para a Font ser padão em todo o sistema

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#214]

**Comment by caiotarifa** [comment]
Por hora será Montserat.
Colocar via `link` no `head` do `index.html` (ver sobre variáveis de ambiente).

**Comment by caiotarifa** [comment]
Lembrei o porque as fontes não podem vir do CDN do Google: offline e aplicativos (Capacitor/Cordova). Vamos manter a estratégia.
