### ISSUE TITLE
Passar as variaveis de estilo e gradiente 

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#215]

**Comment by caiotarifa** [comment]
Quais variáveis e estilos? Consegue listar aqui cada um e para o que serve?

**Comment by caiotarifa** [comment]
Ler antes de implementar: https://forum.quasar-framework.org/topic/3610/create-new-brand-colors/32

Solução: criar mixim.

**Comment by plowzzer** [comment]
Basicamente é esse arquivo aqui @caiotarifa ... preciso ver com detalhe o que faz cada uma dessas variáveis ai
https://github.com/bildvitta/almobi-client/blob/develop/src/css/quasar.variables.scss
