### ISSUE TITLE
Revisar componente de tabela

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#216]
Encontramos esse mixin dentro do Almobi para fazer o scroll lateral funcionar de forma "bela"

```js
export default {
  computed: {
    $_tableMobileMargin () {
      return this.$_isSmall && 'table-spacing--mobile'
    }
  }
}
```

Colocar dentro do componente para não ficar um mixin?

**Comment by caiotarifa** [comment]
Colocar no `QasTable`, mas não como _table_.
