### ISSUE TITLE
Componente de Tooltip

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#217]
Levantado com o pessoal, o tooltip tem um comportamento diferente no mobile, que ao clicado, ele sobre uma "notificação" com a função de notify, verificar se isso deverá ser competencia do asteroid

```js
export default {
  methods: {
    /**
     * Pops up notifications
     * @param {Object} attrs
     * Should receive attributes as Object
     * {message: 'my message something', icon: 'o_icon'}
     */
    $_mobileNotify (attrs) {
      if (this.$_isSmall) {
        this.$q.notify({
          ...attrs
        })
      }
    }
  }
}
```

**Comment by plowzzer** [comment]
Trocar a verificação atual (&_isSmall) para uma verificação se esta dentro de uma plataforma mobile (ou talvez touch).

Verificar o link : https://quasar.dev/options/platform-detection

**Comment by caiotarifa** [comment]
De acordo, mas não acho que precise ser um _mixin_.
