### ISSUE TITLE
Icones não estão com o nome correto

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#222]
Ao começar a trabalhar com o Hub-client, verifiquei que alguns icons daqui do asteriods esta sem o `o_` antes deles (para ser o outlined)

ex.:
`o_apps`
`o_notifications_none`
etc.

Fazer uma varredura nos icones para ver isso e entender o porque que esta funcionando na documentação e não nas importações

**Comment by caiotarifa** [comment]
Quais os componentes que apresentaram esse problema?
