### ISSUE TITLE
DialogRouter Documentation

### ISSUE THREAD

**Issue by caiotarifa** [bildvitta/asteroid#24]
https://github.com/bildvitta/quasar-app-extension-steroids/blob/master/src/components/DialogRouter.vue

**Comment by Lourengato** [comment]
Problemas de reconhecimento das props do componente pelo storybook, ele reconhece mas não é possível alterar as propriedades no stories

**Comment by caiotarifa** [comment]
Pode criar um PR com o que conseguiu fazer e evidenciar o problema?
