### ISSUE TITLE
Correção qas-uploader

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#281]
Corrigir click no header do qas-uploader.

Click de subir uma imagem está sobrepondo o ícone de fazer o upload

**Comment by caiotarifa** [comment]
@leonardoMarco20 pode verificar se isso foi corrigido com o novo PR do @eliasassuncao?

**Comment by leonardoMarco20** [comment]
Ele ainda tem o mesmo comportamento, ao clicar no upload ele abre a janela de escolha de arquivos.

**Comment by leonardoMarco20** [comment]
Observamos outro problema em que o ícone de upload não aparece mesmo add um arquivo após a validação dos credentials.

![image](https://user-images.githubusercontent.com/50151901/121736694-45ea7880-cace-11eb-8ec4-ca21e6f0c7cb.png)
 
Forçando o erro de credentials, o ícone de upload aparece 

![image](https://user-images.githubusercontent.com/50151901/121736851-7cc08e80-cace-11eb-9846-0520d9bf0e1b.png)
