### ISSUE TITLE
Esconder o botão de abrir o menu quando for mobile.

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#318]
Esconder o ícone de abrir o menu quando for mobile. 
![image](https://user-images.githubusercontent.com/50151901/120209488-223d4d80-c205-11eb-8f58-c3226a1f206a.png)

Agora o menu ficara em baixo na tela em modo mobile.

**Comment by gqueiroz1** [comment]
Ainda precisa discutir com o design sobre a validade disso, é possível que todos os sistemas tenham isso sem terem suas telas prejudicadas?

**Comment by DouglasCalora** [comment]
Este componente de bottom não é um componente do asteroid, precisamos discutir para ver se não faz sentido estar dentro do asteroid.
