### ISSUE TITLE
Criar mixin signOut e helper handle-plural.

### ISSUE THREAD

**Issue by leonardoMarco20** [bildvitta/asteroid#334]
No almobi temos um helper para controle de palavras(plural/singular) e um mixin para o controle de CEP.

Também tivemos a ideia de criar um helper para o método de signOut que irá se repetir em todos os sistemas.

**Comment by DouglasCalora** [comment]
@leonardoMarco20 SignOut deve estar dentro da extensão do hub, não acha?

**Comment by DouglasCalora** [comment]
Quais são esses mixins, pode me enviar?
