### ISSUE TITLE
Botão de cancelar em Form-view

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#379]
Pessoal, tava trocando uma ideia aqui com o pessoal do Almobi, tivemos um "probleminha" dentro das telas de formulário...
O botão de "CANCELAR" do form-view tem um comportamento muito especifico, ele retorna ao primeiro pai da rota, exemplo:

```
blabla.com/users/new -> cancelar -> blabla.com/users
blabla.com/users/318273891/edit -> cancelar -> blabla.com/users
```

Ate ai... ok

Isso gerou 2 discuções aqui:
1) Em camadas mais profundas de rota, o que acontece é o seguinte
```
blabla.com/users/381920381/children/new -> cancelar -> blabla.com/users
blabla.com/users/381920381/children/36127863/edit -> cancelar -> blabla.com/users
```

ou seja 
Ele não volta para alistagem do users->id->children, ele volta lá para o users...
Pra isso eu usei o cancel-route para fazer o apontamento correto.

Não seria interessante deixar o componente saber que o cancel volta para a listagem do que ele esta?!

2) A Gabi fez uma pergunta que eu achei interessante levar para uma discução, o cancelar dentro do edit, volta hoje para a listagem, o correto não seria voltar para a single? porque meio que o cara se perde totalmente se ele havia feito uma listagem e pa.

**Comment by gqueiroz1** [comment]
@DouglasCalora essa issue ja foi discutida?

**Comment by DouglasCalora** [comment]
O problema disto é que o usuario pode vir direto para a pagina não tendo historico, a prop já aceita um objeto para configurar esse comportamento necessario.
