### ISSUE TITLE
Comportamento do SelectList

### ISSUE THREAD

**Issue by plowzzer** [bildvitta/asteroid#380]
https://asteroid.nave.dev/?path=/docs/components-selectlist--default

- Precisamos melhorar o comportamento do selectList para escolhas de "todos os items", dos 2 formatos diferentes, o todos funcionando como um elemento * (wildcard) ou um atalho para selecionar todos os valores "atuais"

Obs.: Descrevendo melhor o wildcard: seria um valor em que se traduz "todos", ou seja, selecionado isso, todos os elementos daquela seleção estará ativo, e qualquer novo elemento que entrar nessa lista, tambem estará ativo, diferente do atalho em que se houver um novo elemento, esse não estará ativo.
Ex.: Uma determinada política, tem o intuito de fazer com que os usuários possuam esse privilegio possa de editar usuários, no caso eu posso selecionar os usuários específicos que ele PODE editar ou selecionar o "Todas as entidades", que concede o privilegio de editar TODOS os usuários atuais, e novos do sistema.

- Outro detalhe que levantaram, foi de caso esse wildcard tenha sido ativado, e esteja selecionado na listagem, precisamos que os outros botões fiquem com o status de "disabled"

**Comment by gqueiroz1** [comment]
@DouglasCalora isso aqui ja foi discutido? vocês entenderam a issue?
